# Generated by Django 5.2.5 on 2026-05-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomepageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(max_length=200)),
                (
                    "features_title",
                    models.CharField(default="Facility Features", max_length=200),
                ),
                ("features_description", models.TextField()),
                (
                    "unit_sizes_title",
                    models.CharField(default="Unit Sizes", max_length=200),
                ),
                ("unit_sizes_description", models.TextField()),
                (
                    "contact_title",
                    models.CharField(default="Contact & Hours", max_length=200),
                ),
                ("phone_number", models.CharField(max_length=50)),
                ("address", models.TextField()),
                (
                    "hours_description",
                    models.CharField(
                        blank=True,
                        default="Accessible during hours of operation",
                        max_length=200,
                    ),
                ),
                (
                    "weekday_hours",
                    models.CharField(
                        default="Monday-Saturday: 10am - 6pm", max_length=100
                    ),
                ),
                (
                    "closed_hours",
                    models.CharField(default="Closed Sunday, Holidays", max_length=100),
                ),
                ("map_embed_url", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Homepage Content",
                "verbose_name_plural": "Homepage Content",
            },
        ),
    ]
