# Generated by Django 5.2.5 on 2026-05-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagecontent",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="map_embed_url",
        ),
        migrations.RemoveField(
            model_name="homepagecontent",
            name="unit_sizes_description",
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="google_maps_embed_url",
            field=models.TextField(
                blank=True,
                default="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2604.8854894857686!2d-123.08452968433845!3d49.27185797933135!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54867392e1b9aa13%3A0xa1b3c24f5e8f5f5f!2s2425%20Laurel%20St%2C%20Vancouver%2C%20BC%20V5Z%204M3%2C%20Canada!5e0!3m2!1sen!2sus!4v1692295567890!5m2!1sen!2sus",
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="unit_sizes_text_1",
            field=models.CharField(
                default="Prices range from $60-$490 / month + GST.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="homepagecontent",
            name="unit_sizes_text_2",
            field=models.CharField(
                default="Not sure what size is best? Our storage experts are here to help!",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="address",
            field=models.TextField(
                default="2425 Laurel Street, Vancouver, BC V5Z 4M3, Canada"
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="features_description",
            field=models.TextField(
                default="Broadway Store-All provides a selection of storage units for you to choose from. We are conveniently located in a neighborhood facility located in Fairview Slopes. Whether you need storage for your home or business, we have the space for you."
            ),
        ),
        migrations.AlterField(
            model_name="homepagecontent",
            name="phone_number",
            field=models.CharField(default="778-775-2026", max_length=50),
        ),
    ]
