# Generated by Django 5.2.5 on 2026-05-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_remove_homepagecontent_hero_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="icon",
            field=models.CharField(
                choices=[
                    ("sun", "Sun"),
                    ("shield", "Shield"),
                    ("fire", "Fire"),
                    ("home", "Home"),
                    ("location", "Location"),
                    ("sparkles", "Sparkles"),
                ],
                default="sun",
                max_length=20,
            ),
        ),
    ]
