# Generated by Django 5.2.5 on 2025-08-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, unique=True)),
                ('description', models.TextField()),
                ('dimensions', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
                ('available_units', models.PositiveIntegerField()),
            ],
        ),
    ]
