# Generated by Django 5.2.5 on 2025-12-30 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('available', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_images/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('unit_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='available.unitsize')),
            ],
            options={
                'ordering': ['sort_order', '-is_featured', 'id'],
            },
        ),
    ]
